// Compiled shader for PC, Mac & Linux Standalone

//////////////////////////////////////////////////////////////////////////
// 
// NOTE: This is *not* a valid shader file, the contents are provided just
// for information and for debugging purposes only.
// 
//////////////////////////////////////////////////////////////////////////
// Skipping shader variants that would not be included into build of current scene.

Shader "UI/Default" {
Properties {
[PerRendererData]  _MainTex ("Sprite Texture", 2D) = "white" { }
 _Color ("Tint", Color) = (1.000000,1.000000,1.000000,1.000000)
 _StencilComp ("Stencil Comparison", Float) = 8.000000
 _Stencil ("Stencil ID", Float) = 0.000000
 _StencilOp ("Stencil Operation", Float) = 0.000000
 _StencilWriteMask ("Stencil Write Mask", Float) = 255.000000
 _StencilReadMask ("Stencil Read Mask", Float) = 255.000000
 _ColorMask ("Color Mask", Float) = 15.000000
[Toggle(UNITY_UI_ALPHACLIP)]  _UseUIAlphaClip ("Use Alpha Clip", Float) = 0.000000
}
SubShader { 
 Tags { "QUEUE"="Transparent" "IGNOREPROJECTOR"="true" "RenderType"="Transparent" "PreviewType"="Plane" "CanUseSpriteAtlas"="true" }
 Pass {
  Name "DEFAULT"
  Tags { "QUEUE"="Transparent" "IGNOREPROJECTOR"="true" "RenderType"="Transparent" "PreviewType"="Plane" "CanUseSpriteAtlas"="true" }
  ZTest [unity_GUIZTestMode]
  ZWrite Off
  Cull Off
  Stencil {
   Ref [_Stencil]
   ReadMask [_StencilReadMask]
   WriteMask [_StencilWriteMask]
   Comp [_StencilComp]
   Pass [_StencilOp]
  }
  Blend SrcAlpha OneMinusSrcAlpha
  ColorMask [_ColorMask]
  //////////////////////////////////
  //                              //
  //      Compiled programs       //
  //                              //
  //////////////////////////////////
//////////////////////////////////////////////////////
No keywords set in this variant.
-- Vertex shader for "glcore":
Shader Disassembly:
#ifdef VERTEX
#version 150
#extension GL_ARB_explicit_attrib_location : require
#extension GL_ARB_shader_bit_encoding : enable

uniform 	vec4 hlslcc_mtx4x4unity_ObjectToWorld[4];
uniform 	vec4 hlslcc_mtx4x4unity_MatrixVP[4];
uniform 	vec4 _Color;
in  vec4 in_POSITION0;
in  vec4 in_COLOR0;
in  vec2 in_TEXCOORD0;
out vec4 vs_COLOR0;
out vec2 vs_TEXCOORD0;
out vec4 vs_TEXCOORD1;
vec4 u_xlat0;
vec4 u_xlat1;
void main()
{
    u_xlat0 = in_POSITION0.yyyy * hlslcc_mtx4x4unity_ObjectToWorld[1];
    u_xlat0 = hlslcc_mtx4x4unity_ObjectToWorld[0] * in_POSITION0.xxxx + u_xlat0;
    u_xlat0 = hlslcc_mtx4x4unity_ObjectToWorld[2] * in_POSITION0.zzzz + u_xlat0;
    u_xlat0 = u_xlat0 + hlslcc_mtx4x4unity_ObjectToWorld[3];
    u_xlat1 = u_xlat0.yyyy * hlslcc_mtx4x4unity_MatrixVP[1];
    u_xlat1 = hlslcc_mtx4x4unity_MatrixVP[0] * u_xlat0.xxxx + u_xlat1;
    u_xlat1 = hlslcc_mtx4x4unity_MatrixVP[2] * u_xlat0.zzzz + u_xlat1;
    gl_Position = hlslcc_mtx4x4unity_MatrixVP[3] * u_xlat0.wwww + u_xlat1;
    vs_COLOR0 = in_COLOR0 * _Color;
    vs_TEXCOORD0.xy = in_TEXCOORD0.xy;
    vs_TEXCOORD1 = in_POSITION0;
    return;
}

#endif
#ifdef FRAGMENT
#version 150
#extension GL_ARB_explicit_attrib_location : require
#extension GL_ARB_shader_bit_encoding : enable

uniform 	vec4 _TextureSampleAdd;
uniform  sampler2D _MainTex;
in  vec4 vs_COLOR0;
in  vec2 vs_TEXCOORD0;
layout(location = 0) out vec4 SV_Target0;
vec4 u_xlat0;
vec4 u_xlat10_0;
void main()
{
    u_xlat10_0 = texture(_MainTex, vs_TEXCOORD0.xy);
    u_xlat0 = u_xlat10_0 + _TextureSampleAdd;
    SV_Target0 = u_xlat0 * vs_COLOR0;
    return;
}

#endif


-- Fragment shader for "glcore":
Shader Disassembly:
// All GLSL source is contained within the vertex program

-- Vertex shader for "vulkan":
Uses vertex data channel "Vertex"
Uses vertex data channel "Normal"
Uses vertex data channel "TexCoord"

Set 2D Texture "_MainTex" to set: 0, binding: 0, used in: Fragment 

Constant Buffer "PGlobals1383303232" (16 bytes) on set: 1, binding: 0, used in: Fragment  {
  Vector4 _TextureSampleAdd at 0
}
Constant Buffer "VGlobals1383303232" (144 bytes) on set: 1, binding: 1, used in: Vertex  {
  Matrix4x4 unity_MatrixVP at 64
  Matrix4x4 unity_ObjectToWorld at 0
  Vector4 _Color at 128
}

Shader Disassembly:
Disassembly for Vertex:
// Module Version 10000
// Generated by (magic number): 80001
// Id's are bound by 103

                              Capability Shader
               1:             ExtInstImport  "GLSL.std.450"
                              MemoryModel Logical GLSL450
                              EntryPoint Vertex 4  "main" 11 72 82 87 91 93 95
                              Decorate 11 Location 0
                              Decorate 16 ArrayStride 16
                              Decorate 17 ArrayStride 16
                              MemberDecorate 18 0 Offset 0
                              MemberDecorate 18 1 Offset 64
                              MemberDecorate 18 2 RelaxedPrecision
                              MemberDecorate 18 2 Offset 128
                              Decorate 18 Block
                              Decorate 20 DescriptorSet 1
                              Decorate 20 Binding 1
                              MemberDecorate 70 0 BuiltIn Position
                              MemberDecorate 70 1 BuiltIn PointSize
                              MemberDecorate 70 2 BuiltIn ClipDistance
                              Decorate 70 Block
                              Decorate 82 Location 1
                              Decorate 85 RelaxedPrecision
                              Decorate 87 RelaxedPrecision
                              Decorate 87 Location 0
                              Decorate 91 Location 1
                              Decorate 93 Location 2
                              Decorate 95 Location 2
               2:             TypeVoid
               3:             TypeFunction 2
               6:             TypeFloat 32
               7:             TypeVector 6(float) 4
               8:             TypePointer Private 7(fvec4)
               9:      8(ptr) Variable Private
              10:             TypePointer Input 7(fvec4)
              11:     10(ptr) Variable Input
              14:             TypeInt 32 0
              15:     14(int) Constant 4
              16:             TypeArray 7(fvec4) 15
              17:             TypeArray 7(fvec4) 15
              18:             TypeStruct 16 17 7(fvec4)
              19:             TypePointer Uniform 18(struct)
              20:     19(ptr) Variable Uniform
              21:             TypeInt 32 1
              22:     21(int) Constant 0
              23:     21(int) Constant 1
              24:             TypePointer Uniform 7(fvec4)
              35:     21(int) Constant 2
              44:     21(int) Constant 3
              48:      8(ptr) Variable Private
              68:     14(int) Constant 1
              69:             TypeArray 6(float) 68
              70:             TypeStruct 7(fvec4) 6(float) 69
              71:             TypePointer Output 70(struct)
              72:     71(ptr) Variable Output
              80:             TypePointer Output 7(fvec4)
              82:     10(ptr) Variable Input
              87:     80(ptr) Variable Output
              89:             TypeVector 6(float) 2
              90:             TypePointer Output 89(fvec2)
              91:     90(ptr) Variable Output
              92:             TypePointer Input 89(fvec2)
              93:     92(ptr) Variable Input
              95:     80(ptr) Variable Output
              97:             TypePointer Output 6(float)
               4:           2 Function None 3
               5:             Label
              12:    7(fvec4) Load 11
              13:    7(fvec4) VectorShuffle 12 12 1 1 1 1
              25:     24(ptr) AccessChain 20 22 23
              26:    7(fvec4) Load 25
              27:    7(fvec4) FMul 13 26
                              Store 9 27
              28:     24(ptr) AccessChain 20 22 22
              29:    7(fvec4) Load 28
              30:    7(fvec4) Load 11
              31:    7(fvec4) VectorShuffle 30 30 0 0 0 0
              32:    7(fvec4) FMul 29 31
              33:    7(fvec4) Load 9
              34:    7(fvec4) FAdd 32 33
                              Store 9 34
              36:     24(ptr) AccessChain 20 22 35
              37:    7(fvec4) Load 36
              38:    7(fvec4) Load 11
              39:    7(fvec4) VectorShuffle 38 38 2 2 2 2
              40:    7(fvec4) FMul 37 39
              41:    7(fvec4) Load 9
              42:    7(fvec4) FAdd 40 41
                              Store 9 42
              43:    7(fvec4) Load 9
              45:     24(ptr) AccessChain 20 22 44
              46:    7(fvec4) Load 45
              47:    7(fvec4) FAdd 43 46
                              Store 9 47
              49:    7(fvec4) Load 9
              50:    7(fvec4) VectorShuffle 49 49 1 1 1 1
              51:     24(ptr) AccessChain 20 23 23
              52:    7(fvec4) Load 51
              53:    7(fvec4) FMul 50 52
                              Store 48 53
              54:     24(ptr) AccessChain 20 23 22
              55:    7(fvec4) Load 54
              56:    7(fvec4) Load 9
              57:    7(fvec4) VectorShuffle 56 56 0 0 0 0
              58:    7(fvec4) FMul 55 57
              59:    7(fvec4) Load 48
              60:    7(fvec4) FAdd 58 59
                              Store 48 60
              61:     24(ptr) AccessChain 20 23 35
              62:    7(fvec4) Load 61
              63:    7(fvec4) Load 9
              64:    7(fvec4) VectorShuffle 63 63 2 2 2 2
              65:    7(fvec4) FMul 62 64
              66:    7(fvec4) Load 48
              67:    7(fvec4) FAdd 65 66
                              Store 48 67
              73:     24(ptr) AccessChain 20 23 44
              74:    7(fvec4) Load 73
              75:    7(fvec4) Load 9
              76:    7(fvec4) VectorShuffle 75 75 3 3 3 3
              77:    7(fvec4) FMul 74 76
              78:    7(fvec4) Load 48
              79:    7(fvec4) FAdd 77 78
              81:     80(ptr) AccessChain 72 22
                              Store 81 79
              83:    7(fvec4) Load 82
              84:     24(ptr) AccessChain 20 35
              85:    7(fvec4) Load 84
              86:    7(fvec4) FMul 83 85
                              Store 9 86
              88:    7(fvec4) Load 9
                              Store 87 88
              94:   89(fvec2) Load 93
                              Store 91 94
              96:    7(fvec4) Load 11
                              Store 95 96
              98:     97(ptr) AccessChain 72 22 68
              99:    6(float) Load 98
             100:    6(float) FNegate 99
             101:     97(ptr) AccessChain 72 22 68
                              Store 101 100
                              Return
                              FunctionEnd

Disassembly for Fragment:
// Module Version 10000
// Generated by (magic number): 80001
// Id's are bound by 40

                              Capability Shader
               1:             ExtInstImport  "GLSL.std.450"
                              MemoryModel Logical GLSL450
                              EntryPoint Fragment 4  "main" 17 33 37
                              ExecutionMode 4 OriginUpperLeft
                              Decorate 9 RelaxedPrecision
                              Decorate 13 RelaxedPrecision
                              Decorate 13 DescriptorSet 0
                              Decorate 13 Binding 0
                              Decorate 14 RelaxedPrecision
                              Decorate 17 Location 1
                              Decorate 20 RelaxedPrecision
                              Decorate 21 RelaxedPrecision
                              MemberDecorate 22 0 RelaxedPrecision
                              MemberDecorate 22 0 Offset 0
                              Decorate 22 Block
                              Decorate 24 DescriptorSet 1
                              Decorate 24 Binding 0
                              Decorate 29 RelaxedPrecision
                              Decorate 30 RelaxedPrecision
                              Decorate 31 RelaxedPrecision
                              Decorate 33 RelaxedPrecision
                              Decorate 33 Location 0
                              Decorate 34 RelaxedPrecision
                              Decorate 35 RelaxedPrecision
                              Decorate 37 RelaxedPrecision
                              Decorate 37 Location 0
                              Decorate 38 RelaxedPrecision
               2:             TypeVoid
               3:             TypeFunction 2
               6:             TypeFloat 32
               7:             TypeVector 6(float) 4
               8:             TypePointer Private 7(fvec4)
               9:      8(ptr) Variable Private
              10:             TypeImage 6(float) 2D sampled format:Unknown
              11:             TypeSampledImage 10
              12:             TypePointer UniformConstant 11
              13:     12(ptr) Variable UniformConstant
              15:             TypeVector 6(float) 2
              16:             TypePointer Input 15(fvec2)
              17:     16(ptr) Variable Input
              20:      8(ptr) Variable Private
              22:             TypeStruct 7(fvec4)
              23:             TypePointer Uniform 22(struct)
              24:     23(ptr) Variable Uniform
              25:             TypeInt 32 1
              26:     25(int) Constant 0
              27:             TypePointer Uniform 7(fvec4)
              32:             TypePointer Input 7(fvec4)
              33:     32(ptr) Variable Input
              36:             TypePointer Output 7(fvec4)
              37:     36(ptr) Variable Output
               4:           2 Function None 3
               5:             Label
              14:          11 Load 13
              18:   15(fvec2) Load 17
              19:    7(fvec4) ImageSampleImplicitLod 14 18
                              Store 9 19
              21:    7(fvec4) Load 9
              28:     27(ptr) AccessChain 24 26
              29:    7(fvec4) Load 28
              30:    7(fvec4) FAdd 21 29
                              Store 20 30
              31:    7(fvec4) Load 20
              34:    7(fvec4) Load 33
              35:    7(fvec4) FMul 31 34
                              Store 20 35
              38:    7(fvec4) Load 20
                              Store 37 38
                              Return
                              FunctionEnd

Disassembly for Hull:
Not present.



-- Fragment shader for "vulkan":
Shader Disassembly:
 

//////////////////////////////////////////////////////
Keywords set in this variant: UNITY_UI_ALPHACLIP 
-- Vertex shader for "glcore":
Shader Disassembly:
#ifdef VERTEX
#version 150
#extension GL_ARB_explicit_attrib_location : require
#extension GL_ARB_shader_bit_encoding : enable

uniform 	vec4 hlslcc_mtx4x4unity_ObjectToWorld[4];
uniform 	vec4 hlslcc_mtx4x4unity_MatrixVP[4];
uniform 	vec4 _Color;
in  vec4 in_POSITION0;
in  vec4 in_COLOR0;
in  vec2 in_TEXCOORD0;
out vec4 vs_COLOR0;
out vec2 vs_TEXCOORD0;
out vec4 vs_TEXCOORD1;
vec4 u_xlat0;
vec4 u_xlat1;
void main()
{
    u_xlat0 = in_POSITION0.yyyy * hlslcc_mtx4x4unity_ObjectToWorld[1];
    u_xlat0 = hlslcc_mtx4x4unity_ObjectToWorld[0] * in_POSITION0.xxxx + u_xlat0;
    u_xlat0 = hlslcc_mtx4x4unity_ObjectToWorld[2] * in_POSITION0.zzzz + u_xlat0;
    u_xlat0 = u_xlat0 + hlslcc_mtx4x4unity_ObjectToWorld[3];
    u_xlat1 = u_xlat0.yyyy * hlslcc_mtx4x4unity_MatrixVP[1];
    u_xlat1 = hlslcc_mtx4x4unity_MatrixVP[0] * u_xlat0.xxxx + u_xlat1;
    u_xlat1 = hlslcc_mtx4x4unity_MatrixVP[2] * u_xlat0.zzzz + u_xlat1;
    gl_Position = hlslcc_mtx4x4unity_MatrixVP[3] * u_xlat0.wwww + u_xlat1;
    vs_COLOR0 = in_COLOR0 * _Color;
    vs_TEXCOORD0.xy = in_TEXCOORD0.xy;
    vs_TEXCOORD1 = in_POSITION0;
    return;
}

#endif
#ifdef FRAGMENT
#version 150
#extension GL_ARB_explicit_attrib_location : require
#extension GL_ARB_shader_bit_encoding : enable

uniform 	vec4 _TextureSampleAdd;
uniform  sampler2D _MainTex;
in  vec4 vs_COLOR0;
in  vec2 vs_TEXCOORD0;
layout(location = 0) out vec4 SV_Target0;
vec4 u_xlat0;
vec4 u_xlat10_0;
bool u_xlatb0;
float u_xlat1;
void main()
{
    u_xlat10_0 = texture(_MainTex, vs_TEXCOORD0.xy);
    u_xlat0 = u_xlat10_0 + _TextureSampleAdd;
    u_xlat1 = u_xlat0.w * vs_COLOR0.w + -0.00100000005;
    u_xlat0 = u_xlat0 * vs_COLOR0;
    SV_Target0 = u_xlat0;
    u_xlatb0 = u_xlat1<0.0;
    if((int(u_xlatb0) * int(0xffffffffu))!=0){discard;}
    return;
}

#endif


-- Fragment shader for "glcore":
Shader Disassembly:
// All GLSL source is contained within the vertex program

-- Vertex shader for "vulkan":
Uses vertex data channel "Vertex"
Uses vertex data channel "Normal"
Uses vertex data channel "TexCoord"

Set 2D Texture "_MainTex" to set: 0, binding: 0, used in: Fragment 

Constant Buffer "PGlobals3179562723" (16 bytes) on set: 1, binding: 0, used in: Fragment  {
  Vector4 _TextureSampleAdd at 0
}
Constant Buffer "VGlobals3179562723" (144 bytes) on set: 1, binding: 1, used in: Vertex  {
  Matrix4x4 unity_MatrixVP at 64
  Matrix4x4 unity_ObjectToWorld at 0
  Vector4 _Color at 128
}

Shader Disassembly:
Disassembly for Vertex:
// Module Version 10000
// Generated by (magic number): 80001
// Id's are bound by 103

                              Capability Shader
               1:             ExtInstImport  "GLSL.std.450"
                              MemoryModel Logical GLSL450
                              EntryPoint Vertex 4  "main" 11 72 82 87 91 93 95
                              Decorate 11 Location 0
                              Decorate 16 ArrayStride 16
                              Decorate 17 ArrayStride 16
                              MemberDecorate 18 0 Offset 0
                              MemberDecorate 18 1 Offset 64
                              MemberDecorate 18 2 RelaxedPrecision
                              MemberDecorate 18 2 Offset 128
                              Decorate 18 Block
                              Decorate 20 DescriptorSet 1
                              Decorate 20 Binding 1
                              MemberDecorate 70 0 BuiltIn Position
                              MemberDecorate 70 1 BuiltIn PointSize
                              MemberDecorate 70 2 BuiltIn ClipDistance
                              Decorate 70 Block
                              Decorate 82 Location 1
                              Decorate 85 RelaxedPrecision
                              Decorate 87 RelaxedPrecision
                              Decorate 87 Location 0
                              Decorate 91 Location 1
                              Decorate 93 Location 2
                              Decorate 95 Location 2
               2:             TypeVoid
               3:             TypeFunction 2
               6:             TypeFloat 32
               7:             TypeVector 6(float) 4
               8:             TypePointer Private 7(fvec4)
               9:      8(ptr) Variable Private
              10:             TypePointer Input 7(fvec4)
              11:     10(ptr) Variable Input
              14:             TypeInt 32 0
              15:     14(int) Constant 4
              16:             TypeArray 7(fvec4) 15
              17:             TypeArray 7(fvec4) 15
              18:             TypeStruct 16 17 7(fvec4)
              19:             TypePointer Uniform 18(struct)
              20:     19(ptr) Variable Uniform
              21:             TypeInt 32 1
              22:     21(int) Constant 0
              23:     21(int) Constant 1
              24:             TypePointer Uniform 7(fvec4)
              35:     21(int) Constant 2
              44:     21(int) Constant 3
              48:      8(ptr) Variable Private
              68:     14(int) Constant 1
              69:             TypeArray 6(float) 68
              70:             TypeStruct 7(fvec4) 6(float) 69
              71:             TypePointer Output 70(struct)
              72:     71(ptr) Variable Output
              80:             TypePointer Output 7(fvec4)
              82:     10(ptr) Variable Input
              87:     80(ptr) Variable Output
              89:             TypeVector 6(float) 2
              90:             TypePointer Output 89(fvec2)
              91:     90(ptr) Variable Output
              92:             TypePointer Input 89(fvec2)
              93:     92(ptr) Variable Input
              95:     80(ptr) Variable Output
              97:             TypePointer Output 6(float)
               4:           2 Function None 3
               5:             Label
              12:    7(fvec4) Load 11
              13:    7(fvec4) VectorShuffle 12 12 1 1 1 1
              25:     24(ptr) AccessChain 20 22 23
              26:    7(fvec4) Load 25
              27:    7(fvec4) FMul 13 26
                              Store 9 27
              28:     24(ptr) AccessChain 20 22 22
              29:    7(fvec4) Load 28
              30:    7(fvec4) Load 11
              31:    7(fvec4) VectorShuffle 30 30 0 0 0 0
              32:    7(fvec4) FMul 29 31
              33:    7(fvec4) Load 9
              34:    7(fvec4) FAdd 32 33
                              Store 9 34
              36:     24(ptr) AccessChain 20 22 35
              37:    7(fvec4) Load 36
              38:    7(fvec4) Load 11
              39:    7(fvec4) VectorShuffle 38 38 2 2 2 2
              40:    7(fvec4) FMul 37 39
              41:    7(fvec4) Load 9
              42:    7(fvec4) FAdd 40 41
                              Store 9 42
              43:    7(fvec4) Load 9
              45:     24(ptr) AccessChain 20 22 44
              46:    7(fvec4) Load 45
              47:    7(fvec4) FAdd 43 46
                              Store 9 47
              49:    7(fvec4) Load 9
              50:    7(fvec4) VectorShuffle 49 49 1 1 1 1
              51:     24(ptr) AccessChain 20 23 23
              52:    7(fvec4) Load 51
              53:    7(fvec4) FMul 50 52
                              Store 48 53
              54:     24(ptr) AccessChain 20 23 22
              55:    7(fvec4) Load 54
              56:    7(fvec4) Load 9
              57:    7(fvec4) VectorShuffle 56 56 0 0 0 0
              58:    7(fvec4) FMul 55 57
              59:    7(fvec4) Load 48
              60:    7(fvec4) FAdd 58 59
                              Store 48 60
              61:     24(ptr) AccessChain 20 23 35
              62:    7(fvec4) Load 61
              63:    7(fvec4) Load 9
              64:    7(fvec4) VectorShuffle 63 63 2 2 2 2
              65:    7(fvec4) FMul 62 64
              66:    7(fvec4) Load 48
              67:    7(fvec4) FAdd 65 66
                              Store 48 67
              73:     24(ptr) AccessChain 20 23 44
              74:    7(fvec4) Load 73
              75:    7(fvec4) Load 9
              76:    7(fvec4) VectorShuffle 75 75 3 3 3 3
              77:    7(fvec4) FMul 74 76
              78:    7(fvec4) Load 48
              79:    7(fvec4) FAdd 77 78
              81:     80(ptr) AccessChain 72 22
                              Store 81 79
              83:    7(fvec4) Load 82
              84:     24(ptr) AccessChain 20 35
              85:    7(fvec4) Load 84
              86:    7(fvec4) FMul 83 85
                              Store 9 86
              88:    7(fvec4) Load 9
                              Store 87 88
              94:   89(fvec2) Load 93
                              Store 91 94
              96:    7(fvec4) Load 11
                              Store 95 96
              98:     97(ptr) AccessChain 72 22 68
              99:    6(float) Load 98
             100:    6(float) FNegate 99
             101:     97(ptr) AccessChain 72 22 68
                              Store 101 100
                              Return
                              FunctionEnd

Disassembly for Fragment:
// Module Version 10000
// Generated by (magic number): 80001
// Id's are bound by 67

                              Capability Shader
               1:             ExtInstImport  "GLSL.std.450"
                              MemoryModel Logical GLSL450
                              EntryPoint Fragment 4  "main" 17 38 49
                              ExecutionMode 4 OriginUpperLeft
                              Decorate 9 RelaxedPrecision
                              Decorate 13 RelaxedPrecision
                              Decorate 13 DescriptorSet 0
                              Decorate 13 Binding 0
                              Decorate 14 RelaxedPrecision
                              Decorate 17 Location 1
                              Decorate 20 RelaxedPrecision
                              Decorate 21 RelaxedPrecision
                              MemberDecorate 22 0 RelaxedPrecision
                              MemberDecorate 22 0 Offset 0
                              Decorate 22 Block
                              Decorate 24 DescriptorSet 1
                              Decorate 24 Binding 0
                              Decorate 29 RelaxedPrecision
                              Decorate 30 RelaxedPrecision
                              Decorate 32 RelaxedPrecision
                              Decorate 36 RelaxedPrecision
                              Decorate 38 RelaxedPrecision
                              Decorate 38 Location 0
                              Decorate 41 RelaxedPrecision
                              Decorate 42 RelaxedPrecision
                              Decorate 44 RelaxedPrecision
                              Decorate 45 RelaxedPrecision
                              Decorate 46 RelaxedPrecision
                              Decorate 47 RelaxedPrecision
                              Decorate 49 RelaxedPrecision
                              Decorate 49 Location 0
                              Decorate 50 RelaxedPrecision
                              Decorate 54 RelaxedPrecision
               2:             TypeVoid
               3:             TypeFunction 2
               6:             TypeFloat 32
               7:             TypeVector 6(float) 4
               8:             TypePointer Private 7(fvec4)
               9:      8(ptr) Variable Private
              10:             TypeImage 6(float) 2D sampled format:Unknown
              11:             TypeSampledImage 10
              12:             TypePointer UniformConstant 11
              13:     12(ptr) Variable UniformConstant
              15:             TypeVector 6(float) 2
              16:             TypePointer Input 15(fvec2)
              17:     16(ptr) Variable Input
              20:      8(ptr) Variable Private
              22:             TypeStruct 7(fvec4)
              23:             TypePointer Uniform 22(struct)
              24:     23(ptr) Variable Uniform
              25:             TypeInt 32 1
              26:     25(int) Constant 0
              27:             TypePointer Uniform 7(fvec4)
              31:             TypePointer Private 6(float)
              32:     31(ptr) Variable Private
              33:             TypeInt 32 0
              34:     33(int) Constant 3
              37:             TypePointer Input 7(fvec4)
              38:     37(ptr) Variable Input
              39:             TypePointer Input 6(float)
              43:    6(float) Constant 3129152111
              48:             TypePointer Output 7(fvec4)
              49:     48(ptr) Variable Output
              51:             TypeBool
              52:             TypePointer Private 51(bool)
              53:     52(ptr) Variable Private
              55:    6(float) Constant 0
              58:     25(int) Constant 1
              60:     25(int) Constant 4294967295
               4:           2 Function None 3
               5:             Label
              14:          11 Load 13
              18:   15(fvec2) Load 17
              19:    7(fvec4) ImageSampleImplicitLod 14 18
                              Store 9 19
              21:    7(fvec4) Load 9
              28:     27(ptr) AccessChain 24 26
              29:    7(fvec4) Load 28
              30:    7(fvec4) FAdd 21 29
                              Store 20 30
              35:     31(ptr) AccessChain 20 34
              36:    6(float) Load 35
              40:     39(ptr) AccessChain 38 34
              41:    6(float) Load 40
              42:    6(float) FMul 36 41
              44:    6(float) FAdd 42 43
                              Store 32 44
              45:    7(fvec4) Load 20
              46:    7(fvec4) Load 38
              47:    7(fvec4) FMul 45 46
                              Store 20 47
              50:    7(fvec4) Load 20
                              Store 49 50
              54:    6(float) Load 32
              56:    51(bool) FOrdLessThan 54 55
                              Store 53 56
              57:    51(bool) Load 53
              59:     25(int) Select 57 58 26
              61:     25(int) IMul 59 60
              62:    51(bool) INotEqual 61 26
                              SelectionMerge 64 None
                              BranchConditional 62 63 64
              63:               Label
                                Kill
              64:             Label
                              Return
                              FunctionEnd

Disassembly for Hull:
Not present.



-- Fragment shader for "vulkan":
Shader Disassembly:
 

-- Vertex shader for "glcore":
Shader Disassembly:
#ifdef VERTEX
#version 150
#extension GL_ARB_explicit_attrib_location : require
#extension GL_ARB_shader_bit_encoding : enable

uniform 	vec4 hlslcc_mtx4x4unity_ObjectToWorld[4];
uniform 	vec4 hlslcc_mtx4x4unity_MatrixVP[4];
uniform 	vec4 _Color;
in  vec4 in_POSITION0;
in  vec4 in_COLOR0;
in  vec2 in_TEXCOORD0;
out vec4 vs_COLOR0;
out vec2 vs_TEXCOORD0;
out vec4 vs_TEXCOORD1;
vec4 u_xlat0;
vec4 u_xlat1;
void main()
{
    u_xlat0 = in_POSITION0.yyyy * hlslcc_mtx4x4unity_ObjectToWorld[1];
    u_xlat0 = hlslcc_mtx4x4unity_ObjectToWorld[0] * in_POSITION0.xxxx + u_xlat0;
    u_xlat0 = hlslcc_mtx4x4unity_ObjectToWorld[2] * in_POSITION0.zzzz + u_xlat0;
    u_xlat0 = u_xlat0 + hlslcc_mtx4x4unity_ObjectToWorld[3];
    u_xlat1 = u_xlat0.yyyy * hlslcc_mtx4x4unity_MatrixVP[1];
    u_xlat1 = hlslcc_mtx4x4unity_MatrixVP[0] * u_xlat0.xxxx + u_xlat1;
    u_xlat1 = hlslcc_mtx4x4unity_MatrixVP[2] * u_xlat0.zzzz + u_xlat1;
    gl_Position = hlslcc_mtx4x4unity_MatrixVP[3] * u_xlat0.wwww + u_xlat1;
    vs_COLOR0 = in_COLOR0 * _Color;
    vs_TEXCOORD0.xy = in_TEXCOORD0.xy;
    vs_TEXCOORD1 = in_POSITION0;
    return;
}

#endif
#ifdef FRAGMENT
#version 150
#extension GL_ARB_explicit_attrib_location : require
#extension GL_ARB_shader_bit_encoding : enable

uniform 	vec4 _TextureSampleAdd;
uniform 	vec4 _ClipRect;
uniform  sampler2D _MainTex;
in  vec4 vs_COLOR0;
in  vec2 vs_TEXCOORD0;
in  vec4 vs_TEXCOORD1;
layout(location = 0) out vec4 SV_Target0;
vec4 u_xlat0;
bvec4 u_xlatb0;
vec4 u_xlat1;
vec4 u_xlat10_1;
void main()
{
    u_xlatb0.xy = greaterThanEqual(vs_TEXCOORD1.xyxx, _ClipRect.xyxx).xy;
    u_xlatb0.zw = greaterThanEqual(_ClipRect.zzzw, vs_TEXCOORD1.xxxy).zw;
    u_xlat0 = mix(vec4(0.0, 0.0, 0.0, 0.0), vec4(1.0, 1.0, 1.0, 1.0), vec4(u_xlatb0));
    u_xlat0.xy = u_xlat0.zw * u_xlat0.xy;
    u_xlat0.x = u_xlat0.y * u_xlat0.x;
    u_xlat10_1 = texture(_MainTex, vs_TEXCOORD0.xy);
    u_xlat1 = u_xlat10_1 + _TextureSampleAdd;
    u_xlat1 = u_xlat1 * vs_COLOR0;
    SV_Target0.w = u_xlat0.x * u_xlat1.w;
    SV_Target0.xyz = u_xlat1.xyz;
    return;
}

#endif


-- Fragment shader for "glcore":
Shader Disassembly:
// All GLSL source is contained within the vertex program

-- Vertex shader for "vulkan":
Uses vertex data channel "Vertex"
Uses vertex data channel "Normal"
Uses vertex data channel "TexCoord"

Set 2D Texture "_MainTex" to set: 0, binding: 0, used in: Fragment 

Constant Buffer "PGlobals1415452612" (32 bytes) on set: 1, binding: 0, used in: Fragment  {
  Vector4 _ClipRect at 16
  Vector4 _TextureSampleAdd at 0
}
Constant Buffer "VGlobals1415452612" (144 bytes) on set: 1, binding: 1, used in: Vertex  {
  Matrix4x4 unity_MatrixVP at 64
  Matrix4x4 unity_ObjectToWorld at 0
  Vector4 _Color at 128
}

Shader Disassembly:
Disassembly for Vertex:
// Module Version 10000
// Generated by (magic number): 80001
// Id's are bound by 103

                              Capability Shader
               1:             ExtInstImport  "GLSL.std.450"
                              MemoryModel Logical GLSL450
                              EntryPoint Vertex 4  "main" 11 72 82 87 91 93 95
                              Decorate 11 Location 0
                              Decorate 16 ArrayStride 16
                              Decorate 17 ArrayStride 16
                              MemberDecorate 18 0 Offset 0
                              MemberDecorate 18 1 Offset 64
                              MemberDecorate 18 2 RelaxedPrecision
                              MemberDecorate 18 2 Offset 128
                              Decorate 18 Block
                              Decorate 20 DescriptorSet 1
                              Decorate 20 Binding 1
                              MemberDecorate 70 0 BuiltIn Position
                              MemberDecorate 70 1 BuiltIn PointSize
                              MemberDecorate 70 2 BuiltIn ClipDistance
                              Decorate 70 Block
                              Decorate 82 Location 1
                              Decorate 85 RelaxedPrecision
                              Decorate 87 RelaxedPrecision
                              Decorate 87 Location 0
                              Decorate 91 Location 1
                              Decorate 93 Location 2
                              Decorate 95 Location 2
               2:             TypeVoid
               3:             TypeFunction 2
               6:             TypeFloat 32
               7:             TypeVector 6(float) 4
               8:             TypePointer Private 7(fvec4)
               9:      8(ptr) Variable Private
              10:             TypePointer Input 7(fvec4)
              11:     10(ptr) Variable Input
              14:             TypeInt 32 0
              15:     14(int) Constant 4
              16:             TypeArray 7(fvec4) 15
              17:             TypeArray 7(fvec4) 15
              18:             TypeStruct 16 17 7(fvec4)
              19:             TypePointer Uniform 18(struct)
              20:     19(ptr) Variable Uniform
              21:             TypeInt 32 1
              22:     21(int) Constant 0
              23:     21(int) Constant 1
              24:             TypePointer Uniform 7(fvec4)
              35:     21(int) Constant 2
              44:     21(int) Constant 3
              48:      8(ptr) Variable Private
              68:     14(int) Constant 1
              69:             TypeArray 6(float) 68
              70:             TypeStruct 7(fvec4) 6(float) 69
              71:             TypePointer Output 70(struct)
              72:     71(ptr) Variable Output
              80:             TypePointer Output 7(fvec4)
              82:     10(ptr) Variable Input
              87:     80(ptr) Variable Output
              89:             TypeVector 6(float) 2
              90:             TypePointer Output 89(fvec2)
              91:     90(ptr) Variable Output
              92:             TypePointer Input 89(fvec2)
              93:     92(ptr) Variable Input
              95:     80(ptr) Variable Output
              97:             TypePointer Output 6(float)
               4:           2 Function None 3
               5:             Label
              12:    7(fvec4) Load 11
              13:    7(fvec4) VectorShuffle 12 12 1 1 1 1
              25:     24(ptr) AccessChain 20 22 23
              26:    7(fvec4) Load 25
              27:    7(fvec4) FMul 13 26
                              Store 9 27
              28:     24(ptr) AccessChain 20 22 22
              29:    7(fvec4) Load 28
              30:    7(fvec4) Load 11
              31:    7(fvec4) VectorShuffle 30 30 0 0 0 0
              32:    7(fvec4) FMul 29 31
              33:    7(fvec4) Load 9
              34:    7(fvec4) FAdd 32 33
                              Store 9 34
              36:     24(ptr) AccessChain 20 22 35
              37:    7(fvec4) Load 36
              38:    7(fvec4) Load 11
              39:    7(fvec4) VectorShuffle 38 38 2 2 2 2
              40:    7(fvec4) FMul 37 39
              41:    7(fvec4) Load 9
              42:    7(fvec4) FAdd 40 41
                              Store 9 42
              43:    7(fvec4) Load 9
              45:     24(ptr) AccessChain 20 22 44
              46:    7(fvec4) Load 45
              47:    7(fvec4) FAdd 43 46
                              Store 9 47
              49:    7(fvec4) Load 9
              50:    7(fvec4) VectorShuffle 49 49 1 1 1 1
              51:     24(ptr) AccessChain 20 23 23
              52:    7(fvec4) Load 51
              53:    7(fvec4) FMul 50 52
                              Store 48 53
              54:     24(ptr) AccessChain 20 23 22
              55:    7(fvec4) Load 54
              56:    7(fvec4) Load 9
              57:    7(fvec4) VectorShuffle 56 56 0 0 0 0
              58:    7(fvec4) FMul 55 57
              59:    7(fvec4) Load 48
              60:    7(fvec4) FAdd 58 59
                              Store 48 60
              61:     24(ptr) AccessChain 20 23 35
              62:    7(fvec4) Load 61
              63:    7(fvec4) Load 9
              64:    7(fvec4) VectorShuffle 63 63 2 2 2 2
              65:    7(fvec4) FMul 62 64
              66:    7(fvec4) Load 48
              67:    7(fvec4) FAdd 65 66
                              Store 48 67
              73:     24(ptr) AccessChain 20 23 44
              74:    7(fvec4) Load 73
              75:    7(fvec4) Load 9
              76:    7(fvec4) VectorShuffle 75 75 3 3 3 3
              77:    7(fvec4) FMul 74 76
              78:    7(fvec4) Load 48
              79:    7(fvec4) FAdd 77 78
              81:     80(ptr) AccessChain 72 22
                              Store 81 79
              83:    7(fvec4) Load 82
              84:     24(ptr) AccessChain 20 35
              85:    7(fvec4) Load 84
              86:    7(fvec4) FMul 83 85
                              Store 9 86
              88:    7(fvec4) Load 9
                              Store 87 88
              94:   89(fvec2) Load 93
                              Store 91 94
              96:    7(fvec4) Load 11
                              Store 95 96
              98:     97(ptr) AccessChain 72 22 68
              99:    6(float) Load 98
             100:    6(float) FNegate 99
             101:     97(ptr) AccessChain 72 22 68
                              Store 101 100
                              Return
                              FunctionEnd

Disassembly for Fragment:
// Module Version 10000
// Generated by (magic number): 80001
// Id's are bound by 98

                              Capability Shader
               1:             ExtInstImport  "GLSL.std.450"
                              MemoryModel Logical GLSL450
                              EntryPoint Fragment 4  "main" 13 73 84 95
                              ExecutionMode 4 OriginUpperLeft
                              Decorate 13 Location 2
                              MemberDecorate 16 0 RelaxedPrecision
                              MemberDecorate 16 0 Offset 0
                              MemberDecorate 16 1 Offset 16
                              Decorate 16 Block
                              Decorate 18 DescriptorSet 1
                              Decorate 18 Binding 0
                              Decorate 66 RelaxedPrecision
                              Decorate 70 RelaxedPrecision
                              Decorate 70 DescriptorSet 0
                              Decorate 70 Binding 0
                              Decorate 71 RelaxedPrecision
                              Decorate 73 Location 1
                              Decorate 76 RelaxedPrecision
                              Decorate 77 RelaxedPrecision
                              Decorate 80 RelaxedPrecision
                              Decorate 81 RelaxedPrecision
                              Decorate 83 RelaxedPrecision
                              Decorate 84 RelaxedPrecision
                              Decorate 84 Location 0
                              Decorate 85 RelaxedPrecision
                              Decorate 86 RelaxedPrecision
                              Decorate 95 RelaxedPrecision
                              Decorate 95 Location 0
               2:             TypeVoid
               3:             TypeFunction 2
               6:             TypeBool
               7:             TypeVector 6(bool) 4
               8:             TypePointer Private 7(bvec4)
               9:      8(ptr) Variable Private
              10:             TypeFloat 32
              11:             TypeVector 10(float) 4
              12:             TypePointer Input 11(fvec4)
              13:     12(ptr) Variable Input
              16:             TypeStruct 11(fvec4) 11(fvec4)
              17:             TypePointer Uniform 16(struct)
              18:     17(ptr) Variable Uniform
              19:             TypeInt 32 1
              20:     19(int) Constant 1
              21:             TypePointer Uniform 11(fvec4)
              26:             TypeVector 6(bool) 2
              39:             TypePointer Private 11(fvec4)
              40:     39(ptr) Variable Private
              41:   10(float) Constant 0
              42:   11(fvec4) ConstantComposite 41 41 41 41
              43:   10(float) Constant 1065353216
              44:   11(fvec4) ConstantComposite 43 43 43 43
              48:             TypeVector 10(float) 2
              56:             TypeInt 32 0
              57:     56(int) Constant 1
              58:             TypePointer Private 10(float)
              61:     56(int) Constant 0
              66:     39(ptr) Variable Private
              67:             TypeImage 10(float) 2D sampled format:Unknown
              68:             TypeSampledImage 67
              69:             TypePointer UniformConstant 68
              70:     69(ptr) Variable UniformConstant
              72:             TypePointer Input 48(fvec2)
              73:     72(ptr) Variable Input
              76:     39(ptr) Variable Private
              78:     19(int) Constant 0
              82:     39(ptr) Variable Private
              84:     12(ptr) Variable Input
              89:     56(int) Constant 3
              94:             TypePointer Output 11(fvec4)
              95:     94(ptr) Variable Output
               4:           2 Function None 3
               5:             Label
              14:   11(fvec4) Load 13
              15:   11(fvec4) VectorShuffle 14 14 0 1 0 0
              22:     21(ptr) AccessChain 18 20
              23:   11(fvec4) Load 22
              24:   11(fvec4) VectorShuffle 23 23 0 1 0 0
              25:    7(bvec4) FOrdGreaterThanEqual 15 24
              27:   26(bvec2) VectorShuffle 25 25 0 1
              28:    7(bvec4) Load 9
              29:    7(bvec4) VectorShuffle 28 27 4 5 2 3
                              Store 9 29
              30:     21(ptr) AccessChain 18 20
              31:   11(fvec4) Load 30
              32:   11(fvec4) VectorShuffle 31 31 2 2 2 3
              33:   11(fvec4) Load 13
              34:   11(fvec4) VectorShuffle 33 33 0 0 0 1
              35:    7(bvec4) FOrdGreaterThanEqual 32 34
              36:   26(bvec2) VectorShuffle 35 35 2 3
              37:    7(bvec4) Load 9
              38:    7(bvec4) VectorShuffle 37 36 0 1 4 5
                              Store 9 38
              45:    7(bvec4) Load 9
              46:   11(fvec4) Select 45 44 42
              47:   11(fvec4) ExtInst 1(GLSL.std.450) 46(FMix) 42 44 46
                              Store 40 47
              49:   11(fvec4) Load 40
              50:   48(fvec2) VectorShuffle 49 49 2 3
              51:   11(fvec4) Load 40
              52:   48(fvec2) VectorShuffle 51 51 0 1
              53:   48(fvec2) FMul 50 52
              54:   11(fvec4) Load 40
              55:   11(fvec4) VectorShuffle 54 53 4 5 2 3
                              Store 40 55
              59:     58(ptr) AccessChain 40 57
              60:   10(float) Load 59
              62:     58(ptr) AccessChain 40 61
              63:   10(float) Load 62
              64:   10(float) FMul 60 63
              65:     58(ptr) AccessChain 40 61
                              Store 65 64
              71:          68 Load 70
              74:   48(fvec2) Load 73
              75:   11(fvec4) ImageSampleImplicitLod 71 74
                              Store 66 75
              77:   11(fvec4) Load 66
              79:     21(ptr) AccessChain 18 78
              80:   11(fvec4) Load 79
              81:   11(fvec4) FAdd 77 80
                              Store 76 81
              83:   11(fvec4) Load 76
              85:   11(fvec4) Load 84
              86:   11(fvec4) FMul 83 85
                              Store 82 86
              87:     58(ptr) AccessChain 40 61
              88:   10(float) Load 87
              90:     58(ptr) AccessChain 82 89
              91:   10(float) Load 90
              92:   10(float) FMul 88 91
              93:     58(ptr) AccessChain 82 89
                              Store 93 92
              96:   11(fvec4) Load 82
                              Store 95 96
                              Return
                              FunctionEnd

Disassembly for Hull:
Not present.



-- Fragment shader for "vulkan":
Shader Disassembly:
 

//////////////////////////////////////////////////////
Keywords set in this variant: UNITY_UI_CLIP_RECT UNITY_UI_ALPHACLIP 
-- Vertex shader for "glcore":
Shader Disassembly:
#ifdef VERTEX
#version 150
#extension GL_ARB_explicit_attrib_location : require
#extension GL_ARB_shader_bit_encoding : enable

uniform 	vec4 hlslcc_mtx4x4unity_ObjectToWorld[4];
uniform 	vec4 hlslcc_mtx4x4unity_MatrixVP[4];
uniform 	vec4 _Color;
in  vec4 in_POSITION0;
in  vec4 in_COLOR0;
in  vec2 in_TEXCOORD0;
out vec4 vs_COLOR0;
out vec2 vs_TEXCOORD0;
out vec4 vs_TEXCOORD1;
vec4 u_xlat0;
vec4 u_xlat1;
void main()
{
    u_xlat0 = in_POSITION0.yyyy * hlslcc_mtx4x4unity_ObjectToWorld[1];
    u_xlat0 = hlslcc_mtx4x4unity_ObjectToWorld[0] * in_POSITION0.xxxx + u_xlat0;
    u_xlat0 = hlslcc_mtx4x4unity_ObjectToWorld[2] * in_POSITION0.zzzz + u_xlat0;
    u_xlat0 = u_xlat0 + hlslcc_mtx4x4unity_ObjectToWorld[3];
    u_xlat1 = u_xlat0.yyyy * hlslcc_mtx4x4unity_MatrixVP[1];
    u_xlat1 = hlslcc_mtx4x4unity_MatrixVP[0] * u_xlat0.xxxx + u_xlat1;
    u_xlat1 = hlslcc_mtx4x4unity_MatrixVP[2] * u_xlat0.zzzz + u_xlat1;
    gl_Position = hlslcc_mtx4x4unity_MatrixVP[3] * u_xlat0.wwww + u_xlat1;
    vs_COLOR0 = in_COLOR0 * _Color;
    vs_TEXCOORD0.xy = in_TEXCOORD0.xy;
    vs_TEXCOORD1 = in_POSITION0;
    return;
}

#endif
#ifdef FRAGMENT
#version 150
#extension GL_ARB_explicit_attrib_location : require
#extension GL_ARB_shader_bit_encoding : enable

uniform 	vec4 _TextureSampleAdd;
uniform 	vec4 _ClipRect;
uniform  sampler2D _MainTex;
in  vec4 vs_COLOR0;
in  vec2 vs_TEXCOORD0;
in  vec4 vs_TEXCOORD1;
layout(location = 0) out vec4 SV_Target0;
vec4 u_xlat0;
bvec4 u_xlatb0;
vec4 u_xlat1;
vec4 u_xlat10_1;
float u_xlat2;
void main()
{
    u_xlatb0.xy = greaterThanEqual(vs_TEXCOORD1.xyxx, _ClipRect.xyxx).xy;
    u_xlatb0.zw = greaterThanEqual(_ClipRect.zzzw, vs_TEXCOORD1.xxxy).zw;
    u_xlat0 = mix(vec4(0.0, 0.0, 0.0, 0.0), vec4(1.0, 1.0, 1.0, 1.0), vec4(u_xlatb0));
    u_xlat0.xy = u_xlat0.zw * u_xlat0.xy;
    u_xlat0.x = u_xlat0.y * u_xlat0.x;
    u_xlat10_1 = texture(_MainTex, vs_TEXCOORD0.xy);
    u_xlat1 = u_xlat10_1 + _TextureSampleAdd;
    u_xlat1 = u_xlat1 * vs_COLOR0;
    u_xlat2 = u_xlat1.w * u_xlat0.x + -0.00100000005;
    u_xlat0.x = u_xlat0.x * u_xlat1.w;
    SV_Target0.xyz = u_xlat1.xyz;
    SV_Target0.w = u_xlat0.x;
    u_xlatb0.x = u_xlat2<0.0;
    if((int(u_xlatb0.x) * int(0xffffffffu))!=0){discard;}
    return;
}

#endif


-- Fragment shader for "glcore":
Shader Disassembly:
// All GLSL source is contained within the vertex program

-- Vertex shader for "vulkan":
Uses vertex data channel "Vertex"
Uses vertex data channel "Normal"
Uses vertex data channel "TexCoord"

Set 2D Texture "_MainTex" to set: 0, binding: 0, used in: Fragment 

Constant Buffer "PGlobals1709055069" (32 bytes) on set: 1, binding: 0, used in: Fragment  {
  Vector4 _ClipRect at 16
  Vector4 _TextureSampleAdd at 0
}
Constant Buffer "VGlobals1709055069" (144 bytes) on set: 1, binding: 1, used in: Vertex  {
  Matrix4x4 unity_MatrixVP at 64
  Matrix4x4 unity_ObjectToWorld at 0
  Vector4 _Color at 128
}

Shader Disassembly:
Disassembly for Vertex:
// Module Version 10000
// Generated by (magic number): 80001
// Id's are bound by 103

                              Capability Shader
               1:             ExtInstImport  "GLSL.std.450"
                              MemoryModel Logical GLSL450
                              EntryPoint Vertex 4  "main" 11 72 82 87 91 93 95
                              Decorate 11 Location 0
                              Decorate 16 ArrayStride 16
                              Decorate 17 ArrayStride 16
                              MemberDecorate 18 0 Offset 0
                              MemberDecorate 18 1 Offset 64
                              MemberDecorate 18 2 RelaxedPrecision
                              MemberDecorate 18 2 Offset 128
                              Decorate 18 Block
                              Decorate 20 DescriptorSet 1
                              Decorate 20 Binding 1
                              MemberDecorate 70 0 BuiltIn Position
                              MemberDecorate 70 1 BuiltIn PointSize
                              MemberDecorate 70 2 BuiltIn ClipDistance
                              Decorate 70 Block
                              Decorate 82 Location 1
                              Decorate 85 RelaxedPrecision
                              Decorate 87 RelaxedPrecision
                              Decorate 87 Location 0
                              Decorate 91 Location 1
                              Decorate 93 Location 2
                              Decorate 95 Location 2
               2:             TypeVoid
               3:             TypeFunction 2
               6:             TypeFloat 32
               7:             TypeVector 6(float) 4
               8:             TypePointer Private 7(fvec4)
               9:      8(ptr) Variable Private
              10:             TypePointer Input 7(fvec4)
              11:     10(ptr) Variable Input
              14:             TypeInt 32 0
              15:     14(int) Constant 4
              16:             TypeArray 7(fvec4) 15
              17:             TypeArray 7(fvec4) 15
              18:             TypeStruct 16 17 7(fvec4)
              19:             TypePointer Uniform 18(struct)
              20:     19(ptr) Variable Uniform
              21:             TypeInt 32 1
              22:     21(int) Constant 0
              23:     21(int) Constant 1
              24:             TypePointer Uniform 7(fvec4)
              35:     21(int) Constant 2
              44:     21(int) Constant 3
              48:      8(ptr) Variable Private
              68:     14(int) Constant 1
              69:             TypeArray 6(float) 68
              70:             TypeStruct 7(fvec4) 6(float) 69
              71:             TypePointer Output 70(struct)
              72:     71(ptr) Variable Output
              80:             TypePointer Output 7(fvec4)
              82:     10(ptr) Variable Input
              87:     80(ptr) Variable Output
              89:             TypeVector 6(float) 2
              90:             TypePointer Output 89(fvec2)
              91:     90(ptr) Variable Output
              92:             TypePointer Input 89(fvec2)
              93:     92(ptr) Variable Input
              95:     80(ptr) Variable Output
              97:             TypePointer Output 6(float)
               4:           2 Function None 3
               5:             Label
              12:    7(fvec4) Load 11
              13:    7(fvec4) VectorShuffle 12 12 1 1 1 1
              25:     24(ptr) AccessChain 20 22 23
              26:    7(fvec4) Load 25
              27:    7(fvec4) FMul 13 26
                              Store 9 27
              28:     24(ptr) AccessChain 20 22 22
              29:    7(fvec4) Load 28
              30:    7(fvec4) Load 11
              31:    7(fvec4) VectorShuffle 30 30 0 0 0 0
              32:    7(fvec4) FMul 29 31
              33:    7(fvec4) Load 9
              34:    7(fvec4) FAdd 32 33
                              Store 9 34
              36:     24(ptr) AccessChain 20 22 35
              37:    7(fvec4) Load 36
              38:    7(fvec4) Load 11
              39:    7(fvec4) VectorShuffle 38 38 2 2 2 2
              40:    7(fvec4) FMul 37 39
              41:    7(fvec4) Load 9
              42:    7(fvec4) FAdd 40 41
                              Store 9 42
              43:    7(fvec4) Load 9
              45:     24(ptr) AccessChain 20 22 44
              46:    7(fvec4) Load 45
              47:    7(fvec4) FAdd 43 46
                              Store 9 47
              49:    7(fvec4) Load 9
              50:    7(fvec4) VectorShuffle 49 49 1 1 1 1
              51:     24(ptr) AccessChain 20 23 23
              52:    7(fvec4) Load 51
              53:    7(fvec4) FMul 50 52
                              Store 48 53
              54:     24(ptr) AccessChain 20 23 22
              55:    7(fvec4) Load 54
              56:    7(fvec4) Load 9
              57:    7(fvec4) VectorShuffle 56 56 0 0 0 0
              58:    7(fvec4) FMul 55 57
              59:    7(fvec4) Load 48
              60:    7(fvec4) FAdd 58 59
                              Store 48 60
              61:     24(ptr) AccessChain 20 23 35
              62:    7(fvec4) Load 61
              63:    7(fvec4) Load 9
              64:    7(fvec4) VectorShuffle 63 63 2 2 2 2
              65:    7(fvec4) FMul 62 64
              66:    7(fvec4) Load 48
              67:    7(fvec4) FAdd 65 66
                              Store 48 67
              73:     24(ptr) AccessChain 20 23 44
              74:    7(fvec4) Load 73
              75:    7(fvec4) Load 9
              76:    7(fvec4) VectorShuffle 75 75 3 3 3 3
              77:    7(fvec4) FMul 74 76
              78:    7(fvec4) Load 48
              79:    7(fvec4) FAdd 77 78
              81:     80(ptr) AccessChain 72 22
                              Store 81 79
              83:    7(fvec4) Load 82
              84:     24(ptr) AccessChain 20 35
              85:    7(fvec4) Load 84
              86:    7(fvec4) FMul 83 85
                              Store 9 86
              88:    7(fvec4) Load 9
                              Store 87 88
              94:   89(fvec2) Load 93
                              Store 91 94
              96:    7(fvec4) Load 11
                              Store 95 96
              98:     97(ptr) AccessChain 72 22 68
              99:    6(float) Load 98
             100:    6(float) FNegate 99
             101:     97(ptr) AccessChain 72 22 68
                              Store 101 100
                              Return
                              FunctionEnd

Disassembly for Fragment:
// Module Version 10000
// Generated by (magic number): 80001
// Id's are bound by 119

                              Capability Shader
               1:             ExtInstImport  "GLSL.std.450"
                              MemoryModel Logical GLSL450
                              EntryPoint Fragment 4  "main" 13 73 84 103
                              ExecutionMode 4 OriginUpperLeft
                              Decorate 13 Location 2
                              MemberDecorate 16 0 RelaxedPrecision
                              MemberDecorate 16 0 Offset 0
                              MemberDecorate 16 1 Offset 16
                              Decorate 16 Block
                              Decorate 18 DescriptorSet 1
                              Decorate 18 Binding 0
                              Decorate 66 RelaxedPrecision
                              Decorate 70 RelaxedPrecision
                              Decorate 70 DescriptorSet 0
                              Decorate 70 Binding 0
                              Decorate 71 RelaxedPrecision
                              Decorate 73 Location 1
                              Decorate 76 RelaxedPrecision
                              Decorate 77 RelaxedPrecision
                              Decorate 80 RelaxedPrecision
                              Decorate 81 RelaxedPrecision
                              Decorate 83 RelaxedPrecision
                              Decorate 84 RelaxedPrecision
                              Decorate 84 Location 0
                              Decorate 85 RelaxedPrecision
                              Decorate 86 RelaxedPrecision
                              Decorate 87 RelaxedPrecision
                              Decorate 103 RelaxedPrecision
                              Decorate 103 Location 0
                              Decorate 105 RelaxedPrecision
               2:             TypeVoid
               3:             TypeFunction 2
               6:             TypeBool
               7:             TypeVector 6(bool) 4
               8:             TypePointer Private 7(bvec4)
               9:      8(ptr) Variable Private
              10:             TypeFloat 32
              11:             TypeVector 10(float) 4
              12:             TypePointer Input 11(fvec4)
              13:     12(ptr) Variable Input
              16:             TypeStruct 11(fvec4) 11(fvec4)
              17:             TypePointer Uniform 16(struct)
              18:     17(ptr) Variable Uniform
              19:             TypeInt 32 1
              20:     19(int) Constant 1
              21:             TypePointer Uniform 11(fvec4)
              26:             TypeVector 6(bool) 2
              39:             TypePointer Private 11(fvec4)
              40:     39(ptr) Variable Private
              41:   10(float) Constant 0
              42:   11(fvec4) ConstantComposite 41 41 41 41
              43:   10(float) Constant 1065353216
              44:   11(fvec4) ConstantComposite 43 43 43 43
              48:             TypeVector 10(float) 2
              56:             TypeInt 32 0
              57:     56(int) Constant 1
              58:             TypePointer Private 10(float)
              61:     56(int) Constant 0
              66:     39(ptr) Variable Private
              67:             TypeImage 10(float) 2D sampled format:Unknown
              68:             TypeSampledImage 67
              69:             TypePointer UniformConstant 68
              70:     69(ptr) Variable UniformConstant
              72:             TypePointer Input 48(fvec2)
              73:     72(ptr) Variable Input
              76:     39(ptr) Variable Private
              78:     19(int) Constant 0
              82:     39(ptr) Variable Private
              84:     12(ptr) Variable Input
              87:     58(ptr) Variable Private
              88:     56(int) Constant 3
              94:   10(float) Constant 3129152111
             102:             TypePointer Output 11(fvec4)
             103:    102(ptr) Variable Output
             112:     19(int) Constant 4294967295
               4:           2 Function None 3
               5:             Label
              14:   11(fvec4) Load 13
              15:   11(fvec4) VectorShuffle 14 14 0 1 0 0
              22:     21(ptr) AccessChain 18 20
              23:   11(fvec4) Load 22
              24:   11(fvec4) VectorShuffle 23 23 0 1 0 0
              25:    7(bvec4) FOrdGreaterThanEqual 15 24
              27:   26(bvec2) VectorShuffle 25 25 0 1
              28:    7(bvec4) Load 9
              29:    7(bvec4) VectorShuffle 28 27 4 5 2 3
                              Store 9 29
              30:     21(ptr) AccessChain 18 20
              31:   11(fvec4) Load 30
              32:   11(fvec4) VectorShuffle 31 31 2 2 2 3
              33:   11(fvec4) Load 13
              34:   11(fvec4) VectorShuffle 33 33 0 0 0 1
              35:    7(bvec4) FOrdGreaterThanEqual 32 34
              36:   26(bvec2) VectorShuffle 35 35 2 3
              37:    7(bvec4) Load 9
              38:    7(bvec4) VectorShuffle 37 36 0 1 4 5
                              Store 9 38
              45:    7(bvec4) Load 9
              46:   11(fvec4) Select 45 44 42
              47:   11(fvec4) ExtInst 1(GLSL.std.450) 46(FMix) 42 44 46
                              Store 40 47
              49:   11(fvec4) Load 40
              50:   48(fvec2) VectorShuffle 49 49 2 3
              51:   11(fvec4) Load 40
              52:   48(fvec2) VectorShuffle 51 51 0 1
              53:   48(fvec2) FMul 50 52
              54:   11(fvec4) Load 40
              55:   11(fvec4) VectorShuffle 54 53 4 5 2 3
                              Store 40 55
              59:     58(ptr) AccessChain 40 57
              60:   10(float) Load 59
              62:     58(ptr) AccessChain 40 61
              63:   10(float) Load 62
              64:   10(float) FMul 60 63
              65:     58(ptr) AccessChain 40 61
                              Store 65 64
              71:          68 Load 70
              74:   48(fvec2) Load 73
              75:   11(fvec4) ImageSampleImplicitLod 71 74
                              Store 66 75
              77:   11(fvec4) Load 66
              79:     21(ptr) AccessChain 18 78
              80:   11(fvec4) Load 79
              81:   11(fvec4) FAdd 77 80
                              Store 76 81
              83:   11(fvec4) Load 76
              85:   11(fvec4) Load 84
              86:   11(fvec4) FMul 83 85
                              Store 82 86
              89:     58(ptr) AccessChain 82 88
              90:   10(float) Load 89
              91:     58(ptr) AccessChain 40 61
              92:   10(float) Load 91
              93:   10(float) FMul 90 92
              95:   10(float) FAdd 93 94
                              Store 87 95
              96:     58(ptr) AccessChain 40 61
              97:   10(float) Load 96
              98:     58(ptr) AccessChain 82 88
              99:   10(float) Load 98
             100:   10(float) FMul 97 99
             101:     58(ptr) AccessChain 82 88
                              Store 101 100
             104:   11(fvec4) Load 82
                              Store 103 104
             105:   10(float) Load 87
             106:     6(bool) FOrdLessThan 105 41
             107:    7(bvec4) Load 9
             108:    7(bvec4) CompositeInsert 106 107 0
                              Store 9 108
             109:    7(bvec4) Load 9
             110:     6(bool) CompositeExtract 109 0
             111:     19(int) Select 110 20 78
             113:     19(int) IMul 111 112
             114:     6(bool) INotEqual 113 78
                              SelectionMerge 116 None
                              BranchConditional 114 115 116
             115:               Label
                                Kill
             116:             Label
                              Return
                              FunctionEnd

Disassembly for Hull:
Not present.



-- Fragment shader for "vulkan":
Shader Disassembly:
 

 }
}
}